"""added auth and user

Revision ID: a529f4e71417
Revises: 
Create Date: 2025-02-20 23:32:38.320272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import migration_types


# revision identifiers, used by Alembic.
revision: str = 'a529f4e71417'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', migration_types.AutoString(), nullable=False),
    sa.Column('first_name', migration_types.AutoString(), nullable=True),
    sa.Column('last_name', migration_types.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', migration_types.AutoString(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
